// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package us.longda.tools.proto;

public final class MessageEvent {
  private MessageEvent() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface RequestOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 command_id = 1;
    /**
     * <code>required int32 command_id = 1;</code>
     */
    boolean hasCommandId();
    /**
     * <code>required int32 command_id = 1;</code>
     */
    int getCommandId();

    // required int32 request_data_length = 2;
    /**
     * <code>required int32 request_data_length = 2;</code>
     */
    boolean hasRequestDataLength();
    /**
     * <code>required int32 request_data_length = 2;</code>
     */
    int getRequestDataLength();

    // required bytes request_data = 3;
    /**
     * <code>required bytes request_data = 3;</code>
     */
    boolean hasRequestData();
    /**
     * <code>required bytes request_data = 3;</code>
     */
    com.google.protobuf.ByteString getRequestData();

    // optional bytes attachment = 4;
    /**
     * <code>optional bytes attachment = 4;</code>
     */
    boolean hasAttachment();
    /**
     * <code>optional bytes attachment = 4;</code>
     */
    com.google.protobuf.ByteString getAttachment();

    // repeated string properties = 5;
    /**
     * <code>repeated string properties = 5;</code>
     */
    java.util.List<java.lang.String>
    getPropertiesList();
    /**
     * <code>repeated string properties = 5;</code>
     */
    int getPropertiesCount();
    /**
     * <code>repeated string properties = 5;</code>
     */
    java.lang.String getProperties(int index);
    /**
     * <code>repeated string properties = 5;</code>
     */
    com.google.protobuf.ByteString
        getPropertiesBytes(int index);
  }
  /**
   * Protobuf type {@code protobuff.Request}
   */
  public static final class Request extends
      com.google.protobuf.GeneratedMessage
      implements RequestOrBuilder {
    // Use Request.newBuilder() to construct.
    private Request(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Request(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Request defaultInstance;
    public static Request getDefaultInstance() {
      return defaultInstance;
    }

    public Request getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Request(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              commandId_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              requestDataLength_ = input.readInt32();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              requestData_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              attachment_ = input.readBytes();
              break;
            }
            case 42: {
              if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
                properties_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000010;
              }
              properties_.add(input.readBytes());
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
          properties_ = new com.google.protobuf.UnmodifiableLazyStringList(properties_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return us.longda.tools.proto.MessageEvent.internal_static_protobuff_Request_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return us.longda.tools.proto.MessageEvent.internal_static_protobuff_Request_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              us.longda.tools.proto.MessageEvent.Request.class, us.longda.tools.proto.MessageEvent.Request.Builder.class);
    }

    public static com.google.protobuf.Parser<Request> PARSER =
        new com.google.protobuf.AbstractParser<Request>() {
      public Request parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Request(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Request> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 command_id = 1;
    public static final int COMMAND_ID_FIELD_NUMBER = 1;
    private int commandId_;
    /**
     * <code>required int32 command_id = 1;</code>
     */
    public boolean hasCommandId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 command_id = 1;</code>
     */
    public int getCommandId() {
      return commandId_;
    }

    // required int32 request_data_length = 2;
    public static final int REQUEST_DATA_LENGTH_FIELD_NUMBER = 2;
    private int requestDataLength_;
    /**
     * <code>required int32 request_data_length = 2;</code>
     */
    public boolean hasRequestDataLength() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 request_data_length = 2;</code>
     */
    public int getRequestDataLength() {
      return requestDataLength_;
    }

    // required bytes request_data = 3;
    public static final int REQUEST_DATA_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString requestData_;
    /**
     * <code>required bytes request_data = 3;</code>
     */
    public boolean hasRequestData() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required bytes request_data = 3;</code>
     */
    public com.google.protobuf.ByteString getRequestData() {
      return requestData_;
    }

    // optional bytes attachment = 4;
    public static final int ATTACHMENT_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString attachment_;
    /**
     * <code>optional bytes attachment = 4;</code>
     */
    public boolean hasAttachment() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional bytes attachment = 4;</code>
     */
    public com.google.protobuf.ByteString getAttachment() {
      return attachment_;
    }

    // repeated string properties = 5;
    public static final int PROPERTIES_FIELD_NUMBER = 5;
    private com.google.protobuf.LazyStringList properties_;
    /**
     * <code>repeated string properties = 5;</code>
     */
    public java.util.List<java.lang.String>
        getPropertiesList() {
      return properties_;
    }
    /**
     * <code>repeated string properties = 5;</code>
     */
    public int getPropertiesCount() {
      return properties_.size();
    }
    /**
     * <code>repeated string properties = 5;</code>
     */
    public java.lang.String getProperties(int index) {
      return properties_.get(index);
    }
    /**
     * <code>repeated string properties = 5;</code>
     */
    public com.google.protobuf.ByteString
        getPropertiesBytes(int index) {
      return properties_.getByteString(index);
    }

    private void initFields() {
      commandId_ = 0;
      requestDataLength_ = 0;
      requestData_ = com.google.protobuf.ByteString.EMPTY;
      attachment_ = com.google.protobuf.ByteString.EMPTY;
      properties_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasCommandId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasRequestDataLength()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasRequestData()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, commandId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, requestDataLength_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, requestData_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, attachment_);
      }
      for (int i = 0; i < properties_.size(); i++) {
        output.writeBytes(5, properties_.getByteString(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, commandId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, requestDataLength_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, requestData_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, attachment_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < properties_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(properties_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getPropertiesList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static us.longda.tools.proto.MessageEvent.Request parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static us.longda.tools.proto.MessageEvent.Request parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static us.longda.tools.proto.MessageEvent.Request parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static us.longda.tools.proto.MessageEvent.Request parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static us.longda.tools.proto.MessageEvent.Request parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static us.longda.tools.proto.MessageEvent.Request parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static us.longda.tools.proto.MessageEvent.Request parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static us.longda.tools.proto.MessageEvent.Request parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static us.longda.tools.proto.MessageEvent.Request parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static us.longda.tools.proto.MessageEvent.Request parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(us.longda.tools.proto.MessageEvent.Request prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protobuff.Request}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements us.longda.tools.proto.MessageEvent.RequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return us.longda.tools.proto.MessageEvent.internal_static_protobuff_Request_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return us.longda.tools.proto.MessageEvent.internal_static_protobuff_Request_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                us.longda.tools.proto.MessageEvent.Request.class, us.longda.tools.proto.MessageEvent.Request.Builder.class);
      }

      // Construct using us.longda.tools.proto.MessageEvent.Request.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        commandId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        requestDataLength_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        requestData_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        attachment_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        properties_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return us.longda.tools.proto.MessageEvent.internal_static_protobuff_Request_descriptor;
      }

      public us.longda.tools.proto.MessageEvent.Request getDefaultInstanceForType() {
        return us.longda.tools.proto.MessageEvent.Request.getDefaultInstance();
      }

      public us.longda.tools.proto.MessageEvent.Request build() {
        us.longda.tools.proto.MessageEvent.Request result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public us.longda.tools.proto.MessageEvent.Request buildPartial() {
        us.longda.tools.proto.MessageEvent.Request result = new us.longda.tools.proto.MessageEvent.Request(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.commandId_ = commandId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.requestDataLength_ = requestDataLength_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.requestData_ = requestData_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.attachment_ = attachment_;
        if (((bitField0_ & 0x00000010) == 0x00000010)) {
          properties_ = new com.google.protobuf.UnmodifiableLazyStringList(
              properties_);
          bitField0_ = (bitField0_ & ~0x00000010);
        }
        result.properties_ = properties_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof us.longda.tools.proto.MessageEvent.Request) {
          return mergeFrom((us.longda.tools.proto.MessageEvent.Request)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(us.longda.tools.proto.MessageEvent.Request other) {
        if (other == us.longda.tools.proto.MessageEvent.Request.getDefaultInstance()) return this;
        if (other.hasCommandId()) {
          setCommandId(other.getCommandId());
        }
        if (other.hasRequestDataLength()) {
          setRequestDataLength(other.getRequestDataLength());
        }
        if (other.hasRequestData()) {
          setRequestData(other.getRequestData());
        }
        if (other.hasAttachment()) {
          setAttachment(other.getAttachment());
        }
        if (!other.properties_.isEmpty()) {
          if (properties_.isEmpty()) {
            properties_ = other.properties_;
            bitField0_ = (bitField0_ & ~0x00000010);
          } else {
            ensurePropertiesIsMutable();
            properties_.addAll(other.properties_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasCommandId()) {
          
          return false;
        }
        if (!hasRequestDataLength()) {
          
          return false;
        }
        if (!hasRequestData()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        us.longda.tools.proto.MessageEvent.Request parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (us.longda.tools.proto.MessageEvent.Request) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 command_id = 1;
      private int commandId_ ;
      /**
       * <code>required int32 command_id = 1;</code>
       */
      public boolean hasCommandId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 command_id = 1;</code>
       */
      public int getCommandId() {
        return commandId_;
      }
      /**
       * <code>required int32 command_id = 1;</code>
       */
      public Builder setCommandId(int value) {
        bitField0_ |= 0x00000001;
        commandId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 command_id = 1;</code>
       */
      public Builder clearCommandId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        commandId_ = 0;
        onChanged();
        return this;
      }

      // required int32 request_data_length = 2;
      private int requestDataLength_ ;
      /**
       * <code>required int32 request_data_length = 2;</code>
       */
      public boolean hasRequestDataLength() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 request_data_length = 2;</code>
       */
      public int getRequestDataLength() {
        return requestDataLength_;
      }
      /**
       * <code>required int32 request_data_length = 2;</code>
       */
      public Builder setRequestDataLength(int value) {
        bitField0_ |= 0x00000002;
        requestDataLength_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 request_data_length = 2;</code>
       */
      public Builder clearRequestDataLength() {
        bitField0_ = (bitField0_ & ~0x00000002);
        requestDataLength_ = 0;
        onChanged();
        return this;
      }

      // required bytes request_data = 3;
      private com.google.protobuf.ByteString requestData_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes request_data = 3;</code>
       */
      public boolean hasRequestData() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required bytes request_data = 3;</code>
       */
      public com.google.protobuf.ByteString getRequestData() {
        return requestData_;
      }
      /**
       * <code>required bytes request_data = 3;</code>
       */
      public Builder setRequestData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        requestData_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes request_data = 3;</code>
       */
      public Builder clearRequestData() {
        bitField0_ = (bitField0_ & ~0x00000004);
        requestData_ = getDefaultInstance().getRequestData();
        onChanged();
        return this;
      }

      // optional bytes attachment = 4;
      private com.google.protobuf.ByteString attachment_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes attachment = 4;</code>
       */
      public boolean hasAttachment() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional bytes attachment = 4;</code>
       */
      public com.google.protobuf.ByteString getAttachment() {
        return attachment_;
      }
      /**
       * <code>optional bytes attachment = 4;</code>
       */
      public Builder setAttachment(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        attachment_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes attachment = 4;</code>
       */
      public Builder clearAttachment() {
        bitField0_ = (bitField0_ & ~0x00000008);
        attachment_ = getDefaultInstance().getAttachment();
        onChanged();
        return this;
      }

      // repeated string properties = 5;
      private com.google.protobuf.LazyStringList properties_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensurePropertiesIsMutable() {
        if (!((bitField0_ & 0x00000010) == 0x00000010)) {
          properties_ = new com.google.protobuf.LazyStringArrayList(properties_);
          bitField0_ |= 0x00000010;
         }
      }
      /**
       * <code>repeated string properties = 5;</code>
       */
      public java.util.List<java.lang.String>
          getPropertiesList() {
        return java.util.Collections.unmodifiableList(properties_);
      }
      /**
       * <code>repeated string properties = 5;</code>
       */
      public int getPropertiesCount() {
        return properties_.size();
      }
      /**
       * <code>repeated string properties = 5;</code>
       */
      public java.lang.String getProperties(int index) {
        return properties_.get(index);
      }
      /**
       * <code>repeated string properties = 5;</code>
       */
      public com.google.protobuf.ByteString
          getPropertiesBytes(int index) {
        return properties_.getByteString(index);
      }
      /**
       * <code>repeated string properties = 5;</code>
       */
      public Builder setProperties(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensurePropertiesIsMutable();
        properties_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string properties = 5;</code>
       */
      public Builder addProperties(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensurePropertiesIsMutable();
        properties_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string properties = 5;</code>
       */
      public Builder addAllProperties(
          java.lang.Iterable<java.lang.String> values) {
        ensurePropertiesIsMutable();
        super.addAll(values, properties_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string properties = 5;</code>
       */
      public Builder clearProperties() {
        properties_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string properties = 5;</code>
       */
      public Builder addPropertiesBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensurePropertiesIsMutable();
        properties_.add(value);
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:protobuff.Request)
    }

    static {
      defaultInstance = new Request(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:protobuff.Request)
  }

  public interface ResponseOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 command_id = 1;
    /**
     * <code>required int32 command_id = 1;</code>
     */
    boolean hasCommandId();
    /**
     * <code>required int32 command_id = 1;</code>
     */
    int getCommandId();

    // required int32 response_status = 2;
    /**
     * <code>required int32 response_status = 2;</code>
     */
    boolean hasResponseStatus();
    /**
     * <code>required int32 response_status = 2;</code>
     */
    int getResponseStatus();

    // required int32 response_data_length = 3;
    /**
     * <code>required int32 response_data_length = 3;</code>
     */
    boolean hasResponseDataLength();
    /**
     * <code>required int32 response_data_length = 3;</code>
     */
    int getResponseDataLength();

    // required bytes response_data = 4;
    /**
     * <code>required bytes response_data = 4;</code>
     */
    boolean hasResponseData();
    /**
     * <code>required bytes response_data = 4;</code>
     */
    com.google.protobuf.ByteString getResponseData();

    // optional bytes attachment = 5;
    /**
     * <code>optional bytes attachment = 5;</code>
     */
    boolean hasAttachment();
    /**
     * <code>optional bytes attachment = 5;</code>
     */
    com.google.protobuf.ByteString getAttachment();

    // repeated string properties = 6;
    /**
     * <code>repeated string properties = 6;</code>
     */
    java.util.List<java.lang.String>
    getPropertiesList();
    /**
     * <code>repeated string properties = 6;</code>
     */
    int getPropertiesCount();
    /**
     * <code>repeated string properties = 6;</code>
     */
    java.lang.String getProperties(int index);
    /**
     * <code>repeated string properties = 6;</code>
     */
    com.google.protobuf.ByteString
        getPropertiesBytes(int index);
  }
  /**
   * Protobuf type {@code protobuff.Response}
   */
  public static final class Response extends
      com.google.protobuf.GeneratedMessage
      implements ResponseOrBuilder {
    // Use Response.newBuilder() to construct.
    private Response(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Response(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Response defaultInstance;
    public static Response getDefaultInstance() {
      return defaultInstance;
    }

    public Response getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Response(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              commandId_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              responseStatus_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              responseDataLength_ = input.readInt32();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              responseData_ = input.readBytes();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              attachment_ = input.readBytes();
              break;
            }
            case 50: {
              if (!((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
                properties_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000020;
              }
              properties_.add(input.readBytes());
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
          properties_ = new com.google.protobuf.UnmodifiableLazyStringList(properties_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return us.longda.tools.proto.MessageEvent.internal_static_protobuff_Response_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return us.longda.tools.proto.MessageEvent.internal_static_protobuff_Response_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              us.longda.tools.proto.MessageEvent.Response.class, us.longda.tools.proto.MessageEvent.Response.Builder.class);
    }

    public static com.google.protobuf.Parser<Response> PARSER =
        new com.google.protobuf.AbstractParser<Response>() {
      public Response parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Response(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Response> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 command_id = 1;
    public static final int COMMAND_ID_FIELD_NUMBER = 1;
    private int commandId_;
    /**
     * <code>required int32 command_id = 1;</code>
     */
    public boolean hasCommandId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 command_id = 1;</code>
     */
    public int getCommandId() {
      return commandId_;
    }

    // required int32 response_status = 2;
    public static final int RESPONSE_STATUS_FIELD_NUMBER = 2;
    private int responseStatus_;
    /**
     * <code>required int32 response_status = 2;</code>
     */
    public boolean hasResponseStatus() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 response_status = 2;</code>
     */
    public int getResponseStatus() {
      return responseStatus_;
    }

    // required int32 response_data_length = 3;
    public static final int RESPONSE_DATA_LENGTH_FIELD_NUMBER = 3;
    private int responseDataLength_;
    /**
     * <code>required int32 response_data_length = 3;</code>
     */
    public boolean hasResponseDataLength() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int32 response_data_length = 3;</code>
     */
    public int getResponseDataLength() {
      return responseDataLength_;
    }

    // required bytes response_data = 4;
    public static final int RESPONSE_DATA_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString responseData_;
    /**
     * <code>required bytes response_data = 4;</code>
     */
    public boolean hasResponseData() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required bytes response_data = 4;</code>
     */
    public com.google.protobuf.ByteString getResponseData() {
      return responseData_;
    }

    // optional bytes attachment = 5;
    public static final int ATTACHMENT_FIELD_NUMBER = 5;
    private com.google.protobuf.ByteString attachment_;
    /**
     * <code>optional bytes attachment = 5;</code>
     */
    public boolean hasAttachment() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional bytes attachment = 5;</code>
     */
    public com.google.protobuf.ByteString getAttachment() {
      return attachment_;
    }

    // repeated string properties = 6;
    public static final int PROPERTIES_FIELD_NUMBER = 6;
    private com.google.protobuf.LazyStringList properties_;
    /**
     * <code>repeated string properties = 6;</code>
     */
    public java.util.List<java.lang.String>
        getPropertiesList() {
      return properties_;
    }
    /**
     * <code>repeated string properties = 6;</code>
     */
    public int getPropertiesCount() {
      return properties_.size();
    }
    /**
     * <code>repeated string properties = 6;</code>
     */
    public java.lang.String getProperties(int index) {
      return properties_.get(index);
    }
    /**
     * <code>repeated string properties = 6;</code>
     */
    public com.google.protobuf.ByteString
        getPropertiesBytes(int index) {
      return properties_.getByteString(index);
    }

    private void initFields() {
      commandId_ = 0;
      responseStatus_ = 0;
      responseDataLength_ = 0;
      responseData_ = com.google.protobuf.ByteString.EMPTY;
      attachment_ = com.google.protobuf.ByteString.EMPTY;
      properties_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasCommandId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasResponseStatus()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasResponseDataLength()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasResponseData()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, commandId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, responseStatus_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, responseDataLength_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, responseData_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, attachment_);
      }
      for (int i = 0; i < properties_.size(); i++) {
        output.writeBytes(6, properties_.getByteString(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, commandId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, responseStatus_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, responseDataLength_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, responseData_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, attachment_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < properties_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(properties_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getPropertiesList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static us.longda.tools.proto.MessageEvent.Response parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static us.longda.tools.proto.MessageEvent.Response parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static us.longda.tools.proto.MessageEvent.Response parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static us.longda.tools.proto.MessageEvent.Response parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static us.longda.tools.proto.MessageEvent.Response parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static us.longda.tools.proto.MessageEvent.Response parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static us.longda.tools.proto.MessageEvent.Response parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static us.longda.tools.proto.MessageEvent.Response parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static us.longda.tools.proto.MessageEvent.Response parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static us.longda.tools.proto.MessageEvent.Response parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(us.longda.tools.proto.MessageEvent.Response prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protobuff.Response}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements us.longda.tools.proto.MessageEvent.ResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return us.longda.tools.proto.MessageEvent.internal_static_protobuff_Response_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return us.longda.tools.proto.MessageEvent.internal_static_protobuff_Response_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                us.longda.tools.proto.MessageEvent.Response.class, us.longda.tools.proto.MessageEvent.Response.Builder.class);
      }

      // Construct using us.longda.tools.proto.MessageEvent.Response.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        commandId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        responseStatus_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        responseDataLength_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        responseData_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        attachment_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000010);
        properties_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return us.longda.tools.proto.MessageEvent.internal_static_protobuff_Response_descriptor;
      }

      public us.longda.tools.proto.MessageEvent.Response getDefaultInstanceForType() {
        return us.longda.tools.proto.MessageEvent.Response.getDefaultInstance();
      }

      public us.longda.tools.proto.MessageEvent.Response build() {
        us.longda.tools.proto.MessageEvent.Response result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public us.longda.tools.proto.MessageEvent.Response buildPartial() {
        us.longda.tools.proto.MessageEvent.Response result = new us.longda.tools.proto.MessageEvent.Response(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.commandId_ = commandId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.responseStatus_ = responseStatus_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.responseDataLength_ = responseDataLength_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.responseData_ = responseData_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.attachment_ = attachment_;
        if (((bitField0_ & 0x00000020) == 0x00000020)) {
          properties_ = new com.google.protobuf.UnmodifiableLazyStringList(
              properties_);
          bitField0_ = (bitField0_ & ~0x00000020);
        }
        result.properties_ = properties_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof us.longda.tools.proto.MessageEvent.Response) {
          return mergeFrom((us.longda.tools.proto.MessageEvent.Response)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(us.longda.tools.proto.MessageEvent.Response other) {
        if (other == us.longda.tools.proto.MessageEvent.Response.getDefaultInstance()) return this;
        if (other.hasCommandId()) {
          setCommandId(other.getCommandId());
        }
        if (other.hasResponseStatus()) {
          setResponseStatus(other.getResponseStatus());
        }
        if (other.hasResponseDataLength()) {
          setResponseDataLength(other.getResponseDataLength());
        }
        if (other.hasResponseData()) {
          setResponseData(other.getResponseData());
        }
        if (other.hasAttachment()) {
          setAttachment(other.getAttachment());
        }
        if (!other.properties_.isEmpty()) {
          if (properties_.isEmpty()) {
            properties_ = other.properties_;
            bitField0_ = (bitField0_ & ~0x00000020);
          } else {
            ensurePropertiesIsMutable();
            properties_.addAll(other.properties_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasCommandId()) {
          
          return false;
        }
        if (!hasResponseStatus()) {
          
          return false;
        }
        if (!hasResponseDataLength()) {
          
          return false;
        }
        if (!hasResponseData()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        us.longda.tools.proto.MessageEvent.Response parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (us.longda.tools.proto.MessageEvent.Response) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 command_id = 1;
      private int commandId_ ;
      /**
       * <code>required int32 command_id = 1;</code>
       */
      public boolean hasCommandId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 command_id = 1;</code>
       */
      public int getCommandId() {
        return commandId_;
      }
      /**
       * <code>required int32 command_id = 1;</code>
       */
      public Builder setCommandId(int value) {
        bitField0_ |= 0x00000001;
        commandId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 command_id = 1;</code>
       */
      public Builder clearCommandId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        commandId_ = 0;
        onChanged();
        return this;
      }

      // required int32 response_status = 2;
      private int responseStatus_ ;
      /**
       * <code>required int32 response_status = 2;</code>
       */
      public boolean hasResponseStatus() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 response_status = 2;</code>
       */
      public int getResponseStatus() {
        return responseStatus_;
      }
      /**
       * <code>required int32 response_status = 2;</code>
       */
      public Builder setResponseStatus(int value) {
        bitField0_ |= 0x00000002;
        responseStatus_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 response_status = 2;</code>
       */
      public Builder clearResponseStatus() {
        bitField0_ = (bitField0_ & ~0x00000002);
        responseStatus_ = 0;
        onChanged();
        return this;
      }

      // required int32 response_data_length = 3;
      private int responseDataLength_ ;
      /**
       * <code>required int32 response_data_length = 3;</code>
       */
      public boolean hasResponseDataLength() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int32 response_data_length = 3;</code>
       */
      public int getResponseDataLength() {
        return responseDataLength_;
      }
      /**
       * <code>required int32 response_data_length = 3;</code>
       */
      public Builder setResponseDataLength(int value) {
        bitField0_ |= 0x00000004;
        responseDataLength_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 response_data_length = 3;</code>
       */
      public Builder clearResponseDataLength() {
        bitField0_ = (bitField0_ & ~0x00000004);
        responseDataLength_ = 0;
        onChanged();
        return this;
      }

      // required bytes response_data = 4;
      private com.google.protobuf.ByteString responseData_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes response_data = 4;</code>
       */
      public boolean hasResponseData() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required bytes response_data = 4;</code>
       */
      public com.google.protobuf.ByteString getResponseData() {
        return responseData_;
      }
      /**
       * <code>required bytes response_data = 4;</code>
       */
      public Builder setResponseData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        responseData_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes response_data = 4;</code>
       */
      public Builder clearResponseData() {
        bitField0_ = (bitField0_ & ~0x00000008);
        responseData_ = getDefaultInstance().getResponseData();
        onChanged();
        return this;
      }

      // optional bytes attachment = 5;
      private com.google.protobuf.ByteString attachment_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes attachment = 5;</code>
       */
      public boolean hasAttachment() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional bytes attachment = 5;</code>
       */
      public com.google.protobuf.ByteString getAttachment() {
        return attachment_;
      }
      /**
       * <code>optional bytes attachment = 5;</code>
       */
      public Builder setAttachment(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        attachment_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes attachment = 5;</code>
       */
      public Builder clearAttachment() {
        bitField0_ = (bitField0_ & ~0x00000010);
        attachment_ = getDefaultInstance().getAttachment();
        onChanged();
        return this;
      }

      // repeated string properties = 6;
      private com.google.protobuf.LazyStringList properties_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensurePropertiesIsMutable() {
        if (!((bitField0_ & 0x00000020) == 0x00000020)) {
          properties_ = new com.google.protobuf.LazyStringArrayList(properties_);
          bitField0_ |= 0x00000020;
         }
      }
      /**
       * <code>repeated string properties = 6;</code>
       */
      public java.util.List<java.lang.String>
          getPropertiesList() {
        return java.util.Collections.unmodifiableList(properties_);
      }
      /**
       * <code>repeated string properties = 6;</code>
       */
      public int getPropertiesCount() {
        return properties_.size();
      }
      /**
       * <code>repeated string properties = 6;</code>
       */
      public java.lang.String getProperties(int index) {
        return properties_.get(index);
      }
      /**
       * <code>repeated string properties = 6;</code>
       */
      public com.google.protobuf.ByteString
          getPropertiesBytes(int index) {
        return properties_.getByteString(index);
      }
      /**
       * <code>repeated string properties = 6;</code>
       */
      public Builder setProperties(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensurePropertiesIsMutable();
        properties_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string properties = 6;</code>
       */
      public Builder addProperties(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensurePropertiesIsMutable();
        properties_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string properties = 6;</code>
       */
      public Builder addAllProperties(
          java.lang.Iterable<java.lang.String> values) {
        ensurePropertiesIsMutable();
        super.addAll(values, properties_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string properties = 6;</code>
       */
      public Builder clearProperties() {
        properties_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000020);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string properties = 6;</code>
       */
      public Builder addPropertiesBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensurePropertiesIsMutable();
        properties_.add(value);
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:protobuff.Response)
    }

    static {
      defaultInstance = new Response(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:protobuff.Response)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuff_Request_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protobuff_Request_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuff_Response_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protobuff_Response_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rmessage.proto\022\tprotobuff\"x\n\007Request\022\022\n" +
      "\ncommand_id\030\001 \002(\005\022\033\n\023request_data_length" +
      "\030\002 \002(\005\022\024\n\014request_data\030\003 \002(\014\022\022\n\nattachme" +
      "nt\030\004 \001(\014\022\022\n\nproperties\030\005 \003(\t\"\224\001\n\010Respons" +
      "e\022\022\n\ncommand_id\030\001 \002(\005\022\027\n\017response_status" +
      "\030\002 \002(\005\022\034\n\024response_data_length\030\003 \002(\005\022\025\n\r" +
      "response_data\030\004 \002(\014\022\022\n\nattachment\030\005 \001(\014\022" +
      "\022\n\nproperties\030\006 \003(\t2D\n\016ServiceHandler\0222\n" +
      "\007request\022\022.protobuff.Request\032\023.protobuff" +
      ".ResponseB%\n\025us.longda.tools.protoB\014Mess",
      "ageEvent"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_protobuff_Request_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_protobuff_Request_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_protobuff_Request_descriptor,
              new java.lang.String[] { "CommandId", "RequestDataLength", "RequestData", "Attachment", "Properties", });
          internal_static_protobuff_Response_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_protobuff_Response_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_protobuff_Response_descriptor,
              new java.lang.String[] { "CommandId", "ResponseStatus", "ResponseDataLength", "ResponseData", "Attachment", "Properties", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
